// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Team_Project.Models;

[Index("EntityType", "EntityId", Name = "IX_AuditLogs_EntityType_EntityId")]
[Index("Timestamp", Name = "IX_AuditLogs_Timestamp")]
[Index("UserId", Name = "IX_AuditLogs_UserId")]
public partial class AuditLog
{
    [Key]
    public int Id { get; set; }

    public int? UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string Action { get; set; }

    [Required]
    [StringLength(100)]
    public string EntityType { get; set; }

    public int EntityId { get; set; }

    [StringLength(4000)]
    public string OldValues { get; set; }

    [StringLength(4000)]
    public string NewValues { get; set; }

    [StringLength(45)]
    public string IpAddress { get; set; }

    [StringLength(500)]
    public string UserAgent { get; set; }

    public DateTime Timestamp { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("AuditLogs")]
    public virtual User User { get; set; }
}