// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Team_Project.Models;

[Table("Availability")]
[Index("AvailableDate", Name = "IX_Availability_Date")]
[Index("DoctorId", Name = "IX_Availability_DoctorId")]
[Index("IsBooked", Name = "IX_Availability_IsBooked")]
[Index("DoctorId", "AvailableDate", "StartTime", Name = "UQ_Availability", IsUnique = true)]
public partial class Availability
{
    [Key]
    public int Id { get; set; }

    public int DoctorId { get; set; }

    [Column(TypeName = "date")]
    public DateTime AvailableDate { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    public bool IsBooked { get; set; }

    public int SlotDuration { get; set; }

    public int MaxPatients { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("Availability")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [ForeignKey("DoctorId")]
    [InverseProperty("Availabilities")]
    public virtual Doctor Doctor { get; set; }
}