// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Team_Project.Models;

[Index("DoctorId", Name = "IX_MedicalRecords_DoctorId")]
[Index("IsDeleted", Name = "IX_MedicalRecords_IsDeleted")]
[Index("PatientId", Name = "IX_MedicalRecords_PatientId")]
[Index("RecordDate", Name = "IX_MedicalRecords_RecordDate")]
public partial class MedicalRecord
{
    [Key]
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    public int? AppointmentId { get; set; }

    [Required]
    [StringLength(50)]
    public string RecordType { get; set; }

    [Required]
    [StringLength(2000)]
    public string Diagnosis { get; set; }

    [StringLength(2000)]
    public string Treatment { get; set; }

    [StringLength(2000)]
    public string Prescription { get; set; }

    [StringLength(2000)]
    public string TestResults { get; set; }

    [StringLength(2000)]
    public string Notes { get; set; }

    [StringLength(500)]
    public string AttachmentPath { get; set; }

    public DateTime RecordDate { get; set; }

    public bool IsConfidential { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("AppointmentId")]
    [InverseProperty("MedicalRecords")]
    public virtual Appointment Appointment { get; set; }

    [ForeignKey("DeletedBy")]
    [InverseProperty("MedicalRecords")]
    public virtual User DeletedByNavigation { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("MedicalRecords")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("MedicalRecords")]
    public virtual Patient Patient { get; set; }
}