// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Team_Project.Models;

[Index("DOB", Name = "IX_Patients_DOB")]
[Index("UserId", Name = "IX_Patients_UserId")]
[Index("UserId", Name = "UQ__Patients__1788CC4D4C32BA1F", IsUnique = true)]
public partial class Patient
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [StringLength(10)]
    public string Gender { get; set; }

    [Column(TypeName = "date")]
    public DateTime DOB { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    [StringLength(255)]
    public string EmergencyContact { get; set; }

    [StringLength(20)]
    public string EmergencyPhone { get; set; }

    [StringLength(5)]
    public string BloodType { get; set; }

    [StringLength(1000)]
    public string Allergies { get; set; }

    [StringLength(2000)]
    public string MedicalHistory { get; set; }

    [StringLength(1000)]
    public string CurrentMedications { get; set; }

    [StringLength(255)]
    public string InsuranceProvider { get; set; }

    [StringLength(100)]
    public string InsurancePolicyNumber { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [InverseProperty("Patient")]
    public virtual ICollection<MedicalRecord> MedicalRecords { get; set; } = new List<MedicalRecord>();

    [InverseProperty("Patient")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("UserId")]
    [InverseProperty("Patient")]
    public virtual User User { get; set; }
}