// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVC_Team_Project.Models;

[Index("DoctorId", Name = "IX_Payments_DoctorId")]
[Index("PatientId", Name = "IX_Payments_PatientId")]
[Index("PaymentDate", Name = "IX_Payments_PaymentDate")]
[Index("PaymentStatus", Name = "IX_Payments_Status")]
public partial class Payment
{
    [Key]
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    public int? AppointmentId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Amount { get; set; }

    [Required]
    [StringLength(20)]
    public string PaymentMethod { get; set; }

    [Required]
    [StringLength(20)]
    public string PaymentStatus { get; set; }

    [StringLength(100)]
    public string TransactionId { get; set; }

    public DateTime PaymentDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DueDate { get; set; }

    public DateTime? PaidDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? RefundAmount { get; set; }

    public DateTime? RefundDate { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("AppointmentId")]
    [InverseProperty("Payments")]
    public virtual Appointment Appointment { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("Payments")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("Payments")]
    public virtual Patient Patient { get; set; }
}